ibexa/post-install

COPYRIGHT
LICENSE
README.md

| **JIRA issue**                          | [EZEE-3422](https://issues.ibexa.co/browse/EZEE-3422)
| **Doc needed**                       | no
This PR fixes License files to be Open Source (GPL + BUL) for Ibexa v3.3 release.

EZEE-3422: Prepared LICENSE and COPYRIGHT files for 3.3 release

---

resources/platformsh/ibexa-commerce/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
resources/platformsh/ibexa-content/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/3.3/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3/.platform.app.yaml

JIRA: https://issues.ibexa.co/browse/EZEE-3517

EZEE-3517: Added missing PHP sodium extension

---

composer.json

https://issues.ibexa.co/browse/IBX-596

IBX-596: As a QA I want to change php-cs occurrences into check-cs for consistency

---

.github/pull_request_template.md
.github/workflows/ci.yaml
.github/workflows/ci.yml
phpstan.neon
src/lib/Command/IbexaSetupCommand.php
src/lib/IbexaProductVersion.php

Introduces CI workflow into package.
Increased PHPStan level shows issues with `Ibexa\Platform\PostInstall\IbexaProductVersion` class that popped up in my own installation.
```shell
$ composer ibexa:setup --platformsh
Installing Platform.sh config files...
PHP Fatal error:  Uncaught TypeError: Return value of Ibexa\Platform\PostInstall\IbexaProductVersion::getInstalledProduct() must be of the type string, bool returned in /home/steveb/PhpstormProjects/ezplatform-platform.sh/vendor/ibexa/post-install/src/lib/IbexaProductVersion.php:45
Stack trace:
#0 /home/steveb/PhpstormProjects/ezplatform-platform.sh/vendor/ibexa/post-install/src/lib/Command/IbexaSetupCommand.php(48): Ibexa\Platform\PostInstall\IbexaProductVersion::getInstalledProduct()
#1 …
```

Added Continous Integration

---

resources/platformsh/common/3.3.x-dev/.platform/services.yaml
resources/platformsh/common/3.3/.platform/services.yaml
resources/platformsh/ibexa-commerce/3.3.x-dev/.platform/services.yaml
resources/platformsh/ibexa-commerce/3.3/.platform/services.yaml

| **JIRA issue**                          | ---
I have updated the product name (`eZ` -> `Ibexa`) in Ibexa Cloud `services.yaml` configuration file.

Updated product name

---

.github/workflows/ci.yaml
composer.json

| **JIRA issue**                          | [IBX-XXXX](https://issues.ibexa.co/browse/IBX-XXXX)
| **Type**                                   | feature/bug/improvement
| **Target Ibexa version** | `v4.x` - please update `x` accordingly
| **BC breaks**                          | yes/no

Bumped PHP requirement

---

resources/platformsh/common/4.0.x-dev/.platform/varnish.vcl

IBX-1998: Rebranded routes in ibexa/post-install repository

---

resources/platformsh/common/4.0.x-dev/.platform/varnish.vcl

IBX-2007: Rebranded REST media types in ibexa/post-install repository

---

resources/platformsh/ibexa-commerce/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
resources/platformsh/ibexa-content/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/3.3/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3/.platform.app.yaml

| **JIRA issue**                          | [IBX-XXXX](https://issues.ibexa.co/browse/IBX-XXXX)
| **Target Ibexa version** | `v3.3.13+`

Bumped node version to 14.18.3

---

resources/platformsh/ibexa-commerce/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/4.0.x-dev/.platform.app.yaml

| **JIRA issue**                          | [IBX-XXXX](https://issues.ibexa.co/browse/IBX-XXXX)
| **Target Ibexa version** | `v4.x`

Bumped node version to 14.18.3 (4.0.x-dev)

---

resources/platformsh/ibexa-commerce/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/4.0.x-dev/.platform.app.yaml

IBX-1853: Used rebranded Ibexa name in codebase

---

resources/platformsh/common/4.0.x-dev/config/packages/http.yaml

| **JIRA issue**                          | [IBX-2224](https://issues.ibexa.co/browse/IBX-2224)
| **Target Ibexa version** | `v4.0`

IBX-2224: Added configuration for framework.trusted_proxies

---

.github/workflows/pr-assign.yaml
.github/workflows/release.yml

| **JIRA issue**                          | IBX-2822
| **Target Ibexa version** | `any`
| **Doc needed**                       | no
This will add changelog generator workflow, that will be triggered when a new tag is created

IBX-2822: Added changelog generator

---

.github/workflows/upmerge.yml

This will add Upmerge workflow.
It's configured at this moment, to upmerge `main` branch to `nightly`.

Added Upmerge workflow

---

resources/platformsh/ibexa-commerce/4.4.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/4.4.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/4.4.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/4.4.x-dev/.platform.app.yaml

| **JIRA issue**                          | -
| **Target Ibexa version** | `v4.4`

Fixed references to old documentation in .platform.app.yaml

---

resources/platformsh/ibexa-commerce/5.0/.platform.app.yaml
resources/platformsh/ibexa-experience/5.0/.platform.app.yaml
resources/platformsh/ibexa-headless/5.0/.platform.app.yaml
resources/platformsh/ibexa-oss/5.0/.platform.app.yaml

| :ticket: Issue | IBX-8218 |
Use PHP 8.3 as baseline for new projects.
Scope: new project setup on p.sh
N/A

Bump PHP version in p.sh configuration

---

resources/platformsh/ibexa-commerce/4.6/.platform.app.yaml
resources/platformsh/ibexa-experience/4.6/.platform.app.yaml
resources/platformsh/ibexa-headless/4.6/.platform.app.yaml
resources/platformsh/ibexa-oss/4.6/.platform.app.yaml

| :ticket: Issue | N/A |
Preparation for releasing 4.6 on PHP 8.3 (cherry picked from commit 35531e8d0020de82dccbef9f66edb6ea6a03e3cd)

Bump PHP version in p.sh configuration for 4.6 branch

---

resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
resources/platformsh/ibexa-content/3.3/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3/.platform.app.yaml

It was done for 4.6 and main in separate PRs.

Bump PHP version in p.sh configuration for 1.0 branch (DXP 3.3)

---

resources/platformsh/ibexa-commerce/3.3/.platform/configsets/solr6/conf/schema.xml

| **JIRA issue**                          | [IBX-7806](https://issues.ibexa.co/browse/IBX-7806)
| **Target Ibexa version** | `v3.3` - please update `x` accordingly

IBX-7806: Added missing random fields in solr schema

---

resources/platformsh/common/4.6/.platform/varnish.vcl

| :ticket: Issue | IBX-8885 |
It was properly merged up, and even made it's way to 4.6.0-beta3 (https://github.com/ibexa/post-install/commit/5c1108e509db4c898bccb5494d581d2ab5dfbab8), but then was probably deleted during cleanup here:
https://github.com/ibexa/post-install/pull/69

IBX-8885: Restored ibexa cookies rule

---

resources/platformsh/common/5.0/.platform/varnish.vcl

| :ticket: Issue | IBX-8811 |
- https://github.com/ibexa/core/pull/420

IBX-8811: Rebranded SiteAccess session prefix

---

rector.php

| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. 
Sanities.
N/A

 IBX-9968: Resolved Symfony 7.x deprecations
