src/lib/Command/IbexaSetupCommand.php

> JIRA: https://issues.ibexa.co/browse/EZP-32343
It was returning 1 (general error) instead of 0 (success).

EZP-32343: Fixed return code for ibexa:setup command

---

resources/platformsh/ibexa-commerce/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml

| **JIRA issue**                          | [IBX-772](https://issues.ibexa.co/browse/IBX-772)
| **Target Ibexa version** | `v4.0`
There is a deadline in the comment of platform.app.yaml generated for ibexa commerce. I checked the others and it seems there are fine. 
ping @ibexa/engineering

IBX-772: Fixes bad link to composer auth var setup

---

resources/platformsh/ibexa-commerce/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
resources/platformsh/ibexa-content/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/3.3/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3/.platform.app.yaml

| **Target Ibexa version** | `v4.0` 
Just noticed this thing in the .platform.app.yaml we provide. All the commands that involves Symfony `bin/console` are preceded by `php` except the ones related to `foshttpcache`. 
I'm not creating a ticket for this as I don't see the need but let me know if you prefer me to do it. 
Also I'm doing pr against 1.0 branch. Let me know if that's ok for you .
ping @ibexa/engineering

[Doc] Added php at the beggining of command to clear http cache

---

resources/platformsh/ibexa-commerce/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/4.0.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/4.0.x-dev/.platform.app.yaml

| **JIRA issue**                          | [IBX-840](https://issues.ibexa.co/browse/IBX-840)
| **Target Ibexa version** | `v4.0`
Updates the current version of NodeJS used on platform.sh instances to current LTS version
This prevents issues:
```
Downloading and installing node v10.15.3...
W: Downloading https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz...
https://console.platform.sh/ez-platform-sh-dev-account/v5p5smejfqk2u/master
W: !!  error @ckeditor/ckeditor5-alignment@26.0.0: The engine "node" is incompatible with this module. Expected version …
```

Switched to current NodeJS LTS version

---

resources/platformsh/ibexa-commerce/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
resources/platformsh/ibexa-content/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/3.3/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3/.platform.app.yaml

| **JIRA issue**                          | [IBX-1378](https://issues.ibexa.co/browse/IBX-1378)
As PHP 7.3 will no longer receive any updates from December, the default version has been changed to 7.4

IBX-1378: changed PHP version to 7.4

---

resources/platformsh/common/3.3.x-dev/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/common/3.3/bin/platformsh_prestart_cacheclear.sh

| **JIRA issue**                          | [IBX-301](https://issues.ibexa.co/browse/IBX-301)
When the` cache:clear` command is executed it is making a check if cache "is fresh":
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L132
When we execute `rm -rf var/cache/prod/*.*` beforehand cache:clear script is "tricked" into thinking that cache is fresh, as the request timestamp will be lower than Container File modification timestamp.
```
bulbo@bulboPC:~/www/experience-3.3$ rm -rf …
```

IBX-301 Changed cache clearing command to avoid cache issues on the deploy

---

.gitignore
composer.json

| **JIRA issue**                          | -
| **Target Ibexa version** | `v4.0`+
Fixed reference to non-existing .php_cs file in `composer check-cs`/`composer check-cs-changed` command

Fixed composer check-cs/check-cs-changed command

---

resources/platformsh/ibexa-oss/3.3.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3/.platform.app.yaml

| **JIRA issue**                          | [IBX-2919](https://issues.ibexa.co/browse/IBX-2919)
Added missing PHP sodium extension for OSS edition.

IBX-2919: Added missing PHP sodium extension for OSS edition

---

resources/platformsh/common/4.1.x-dev/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/common/4.1/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/ibexa-commerce/4.1.x-dev/.platform.app.yaml
resources/platformsh/ibexa-commerce/4.1/.platform.app.yaml
resources/platformsh/ibexa-content/4.1.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/4.1/.platform.app.yaml
resources/platformsh/ibexa-experience/4.1.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/4.1/.platform.app.yaml
resources/platformsh/ibexa-oss/4.1.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/4.1/.platform.app.yaml

| **JIRA issue**                          | [IBX-301](https://issues.ibexa.co/browse/IBX-301)
| **Target Ibexa version** | `v4.1` 
Looks like the fix for bad cache cleared got lost on the way (https://github.com/ibexa/post-install/pull/22 - not sure how).
Description from the previous PR:
> When the cache:clear command is executed it is making a check if cache "is fresh":
> https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L132
> 
> When we execute rm -rf var/cache/prod/*.* beforehand cache:clear script is "tricked" into …

IBX-301: Fixed manual cache clearing

---

resources/platformsh/common/4.2.0-beta1/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/common/4.2.0-rc1/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/common/4.2.0/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/common/4.2.x-dev/bin/platformsh_prestart_cacheclear.sh
resources/platformsh/ibexa-commerce/4.2.0-beta1/.platform.app.yaml
resources/platformsh/ibexa-commerce/4.2.0-rc1/.platform.app.yaml
resources/platformsh/ibexa-commerce/4.2.0/.platform.app.yaml
resources/platformsh/ibexa-commerce/4.2.x-dev/.platform.app.yaml
resources/platformsh/ibexa-content/4.2.0-beta1/.platform.app.yaml
resources/platformsh/ibexa-content/4.2.0-rc1/.platform.app.yaml
resources/platformsh/ibexa-content/4.2.0/.platform.app.yaml
resources/platformsh/ibexa-content/4.2.x-dev/.platform.app.yaml
resources/platformsh/ibexa-experience/4.2.0-beta1/.platform.app.yaml
resources/platformsh/ibexa-experience/4.2.0-rc1/.platform.app.yaml
resources/platformsh/ibexa-experience/4.2.0/.platform.app.yaml
resources/platformsh/ibexa-experience/4.2.x-dev/.platform.app.yaml
resources/platformsh/ibexa-oss/4.2.0-beta1/.platform.app.yaml
resources/platformsh/ibexa-oss/4.2.0-rc1/.platform.app.yaml
resources/platformsh/ibexa-oss/4.2.0/.platform.app.yaml
resources/platformsh/ibexa-oss/4.2.x-dev/.platform.app.yaml

Merge up PR for: https://github.com/ibexa/post-install/pull/51

IBX-301: Fixed manual cache clearing - merge up

---

composer.json
phpstan.neon

| **JIRA issue**                          | N/A
| **Target Ibexa version** | `v4.3`
Updated PHPStan, which fixes the issue found in #57.

Fixed PHPStan failing on PHP 8.1

---

resources/platformsh/common/4.5.x-dev/.platform/varnish.vcl
resources/platformsh/common/4.5/.platform/varnish.vcl

| **JIRA issue**                          | [IBX-5854](https://issues.ibexa.co/browse/IBX-5854)
| **Target Ibexa version** | `v4.5` - please update `x` accordingly
As a part of unifying our backoffice cookies names - we should now allow passing all prefixed with `ibexa-` between varnish/fastly and backend.

IBX-5854: Allowed `ibexa-` prefixed cookies

---

resources/platformsh/common/3.3.x-dev/.platform/services.yaml
resources/platformsh/common/3.3/.platform/services.yaml
resources/platformsh/ibexa-commerce/3.3.x-dev/.platform/services.yaml
resources/platformsh/ibexa-commerce/3.3/.platform/services.yaml

…
| **JIRA issue**                          | [IBX-7298](https://issues.ibexa.co/browse/IBX-7298)
| **Target Ibexa version** | `v3.3`, `v4.5`
Logic in `app/config/env/platformsh.php` was moved to `EzSystems\EzPlatformCoreBundle\DependencyInjection\EzPlatformCoreExtension` in Ibexa DXP 3.x and to `Ibexa\Bundle\Core\DependencyInjection\IbexaCoreExtension in Ibexa DXP` 4.x
This means that comment needs to be changed when merging to 4.5 branch ...

IBX-7298: Comment in .platform/services.yaml referes to non-existent file

---

resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
resources/platformsh/ibexa-content/3.3/.platform.app.yaml
resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
resources/platformsh/ibexa-oss/3.3/.platform.app.yaml

| :ticket: Issue | IBX-8506 |
- https://github.com/ibexa/documentation-developer/pull/2423
The PHP config for Ibexa Cloud should default to not display errors in production. This is normally of no consequence as Symfony controls error handling, but in exceptional situations Symfony may fail and PHP's error handling take over. So to be on the safe side the default should be to not display errors.
See Doc note below. And note that you will have to crash Symfony to reproduce the change.
See related doc PR (merged). Note also that these config files do not detect prod/dev mode, so display_errors will now by default be disabled regardless of mode, this should be noted in release notes.

IBX-8506: Disabled display_errors in Cloud

---

src/lib/Command/IbexaSetupCommand.php

| :ticket: Issue | IBX-8138 |
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.

IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

---

resources/templates/apache2/vhost.template
resources/templates/nginx/ibexa_params.d/ibexa_rewrite_params

| **JIRA issue**                          | [IBX-7818](https://issues.ibexa.co/browse/IBX-7818)
| **Target Ibexa version** | `v4.6`
Fixed an issue when index.php can be accessed directly if the URL is long and complexe enough
@ibexa/engineering can you review this PR ? thank you

IBX-7818: Fixed direct acces to index.php with long URL

---

resources/templates/apache2/vhost.template
resources/templates/nginx/vhost.template

Removed the outdated mentions of PHP 5.
The socket name is taken from: https://php.watch/articles/php-8.3-install-upgrade-on-debian-ubuntu#sapis

Updated outdated mentions of PHP 5

---

.github/workflows/ci.yaml
composer.json
src/lib/Command/IbexaSetupCommand.php
src/lib/CommandProvider.php
src/lib/PostInstall.php

> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
| :ticket: Issue | IBX-8470 |
This PR bumps Symfony to v6 with optional codebase upgrades. The package doesn't depend on the other ibexa packages.
Key changes:
Sanities in the form of regression tests.
No documentation required.

IBX-8470: Upgraded codebase to Symfony 6

---

.github/workflows/ci.yaml
composer.json
rector.php
src/lib/Command/IbexaSetupCommand.php

| :ticket: Issue | IBX-9584  |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [CLI] Replaced deprecated Command::{$defaultName, $defaultDescription} with the AsCommand attribute
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+.
Sanities.
N/A

IBX-9584: Resolved Symfony 6.x deprecations

---

.github/workflows/ci.yaml
resources/platformsh/ibexa-commerce/5.0/.platform.app.yaml
resources/platformsh/ibexa-experience/5.0/.platform.app.yaml
resources/platformsh/ibexa-headless/5.0/.platform.app.yaml
resources/platformsh/ibexa-oss/5.0/.platform.app.yaml

| :ticket: Issue | IBX-9898 |
- https://github.com/ibexa/core/pull/525

IBX-9898: Adjusted `ibexa:install` command to run in non-interactive mode for Ibexa Cloud

---

resources/platformsh/ibexa-commerce/5.0/.platform.app.yaml
resources/platformsh/ibexa-experience/5.0/.platform.app.yaml
resources/platformsh/ibexa-headless/5.0/.platform.app.yaml
resources/platformsh/ibexa-oss/5.0/.platform.app.yaml
src/lib/Command/IbexaSetupCommand.php

| :ticket: Issue | IBX-9942 |
https://github.com/ibexa/oss/pull/218
Updated deployment process to use Symfony Cloud configurator and symfony-deploy

IBX-9942: Updated deployment process to use Symfony Cloud configurator and symfony-deploy

---

resources/platformsh/common/5.0/.platform/varnish.vcl

| :ticket: Issue | IBX-XXXXX |
- ibexa/http-cache#64
- ibexa/fastly#45
- ibexa/post-install#96
- ibexa/docker#42

Rebranded VCL

---

resources/platformsh/common/5.0/.platform/services.yaml
resources/platformsh/ibexa-commerce/5.0/.platform.app.yaml
resources/platformsh/ibexa-commerce/5.0/.platform/services.yaml
resources/platformsh/ibexa-experience/5.0/.platform.app.yaml
resources/platformsh/ibexa-headless/5.0/.platform.app.yaml
resources/platformsh/ibexa-oss/5.0/.platform.app.yaml

| :ticket: Issue | IBX-XXXXX |
Bumped for v5:
- Solr from 7.7 to 8.11
- MariaDB from 10.4 to 10.11
- Redis from 5.0 to 7.2
- Elastic from 7.7 to 7.17
Varnish stays 6.0 (v5 supports 6.0 & 7.2).
Ref.
https://docs.platform.sh/add-services/solr.html#supported-versions
https://docs.platform.sh/add-services/mysql.html#supported-versions
https://docs.platform.sh/add-services/redis.html#supported-versions
https://docs.platform.sh/add-services/elasticsearch.html#supported-versions
https://docs.platform.sh/add-services/varnish.html#supported-versions
Disabled default GraphQL schema generation also.
TODO:

[5.0] Bump Solr, MariaDB, Redis & Elastic versions  for v5. Disable GQL schema generation
